export { buildSentinelMessage, purposeBody } from './format.js';
export type { SentinelMessage, BuildSentinelOpts, FolderPurpose } from './format.js';
export { SentinelStore } from './store.js';
export type { Sentinel, SentinelRow } from './store.js';
export { appendSentinel, findSentinel, deleteSentinel, runSentinelSelfTest } from './imap-ops.js';
export type { AppendSentinelResult } from './imap-ops.js';
export { collectTrackedFolders, reconcileSentinels } from './lifecycle.js';
export { isSentinel, isSentinelRaw, SENTINEL_HEADER } from './detect.js';
export { SentinelScanner } from './scanner.js';
export type { ScanResult, ScanReport, ScanStatus, SentinelScannerDeps, SentinelScannerState } from './scanner.js';
